# 服务端口号
server:
  port: 9527
  path: /Spring_Boot_Demo_02
  servlet:
    session:
      timeout: 20s
# 数据库地址
datasource:
  url: localhost:3306

spring:
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Hinge_db
    username: root
    password: Zhy20020410@
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000
    type: com.alibaba.druid.pool.DruidDataSource

batis:
  # 指定别名设置的包为所有entity
  type-aliases-package: SpringBoot_Demo_02.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范spring:

mapper-locations: # mapper映射文件位置
  - classpath:mapper/*.xml